CATALYST = "<http://base.namespace.com/Catalyst>"
CO_CATALYST = "<http://base.namespace.com/Catalyst>"
DOPANT = "http://base.namespace.com/Dopant"
DYE = "http://base.namespace.com/Dye"
REDUCTANT = "http://base.namespace.com/Reductant"
SUPPORT = "http://base.namespace.com/Support"